apiVersion: apps/v1
kind: Deployment
metadata:
    name: payments-depl
spec:
    replicas: 1
    selector:
        matchLabels:
            app: payments
    template:
        metadata:
            labels:
                app: payments
        spec:
            containers:
                - name: payments
                  image: 0866500635/ticket-payments
                  env:
                      - name: MONGO_URI
                        value: 'mongodb://auth-mongo-srv:27017/payments-service'
                      - name: RABBIT_URI
                        value: 'amqp://rabbitmq-srv:5672'
                      - name: JWT_KEY
                        valueFrom:
                            secretKeyRef:
                                name: jwt-secret
                                key: JWT_KEY
                      - name: STRIPE_KEY
                        valueFrom:
                            secretKeyRef:
                                name: stripe-secret
                                key: STRIPE_KEY
---
apiVersion: v1
kind: Service
metadata:
    name: payments-srv
spec:
    selector:
        app: payments
    type: ClusterIP
    ports:
        - name: payments
          protocol: TCP
          port: 3000
          targetPort: 3000
